### ISSUE TITLE
Disambiguate Windows Hello AAGUIDs

### ISSUE THREAD

**Issue by MasterKale** [passkeydeveloper/passkey-authenticator-aaguids#1]
There are four Windows Hello entries with identical `friendlyName` and `verboseName` of `"Windows Hello"`:

```json
    "08987058-cadc-4b81-b6e1-30de50dcbe96": {
        "platform": "Windows",
        "friendlyName": "Windows Hello",
        "verboseName": "Windows Hello"
    },
    "9ddd1817-af5a-4672-a2b9-3e3dd95000a9": {
        "platform": "Windows",
        "friendlyName": "Windows Hello",
        "verboseName": "Windows Hello"
    },
    "6e96969e-a5cf-4aad-9b56-305fe6c82795": {
        "platform": "Windows",
        "friendlyName": "Windows Hello",
        "verboseName": "Windows Hello"
    },
    "6028b017-b1d4-4c02-b4b3-afcdafc96bb2": {
        "platform": "Windows",
        "friendlyName": "Windows Hello",
        "verboseName": "Windows Hello"
    }
```

Can additional info be added to the `verboseName`'s to help RP's understand why Windows Hello gets 4 AAGUID's?

**Comment by timcappalli** [comment]
@MasterKale for end users, there is no difference, it is just Windows Hello, so I'm hesitant to get into technical details here. If you need those full details about the implementation, MDS is the correct place to get that information.

**Comment by timcappalli** [comment]
Actually, might just get rid of both verboseName and platform as the only thing that really matters is the name. Thoughts?

**Comment by MasterKale** [comment]
> If you need those full details about the implementation, MDS is the correct place to get that information.

Oh, if going to MDS to understand the differences is going to be an option in the future then I'd say you can close this issue.

> Actually, going to get rid of both verboseName and platform as the only thing that really matters is the name.

Yeah, interesting proposal. I see you already did it so for what it's worth I suppose it's fine to remove those concepts and just keep this list "suggested nicknames" (at least that's how I'm interpreting the values without a README to tell me the intent of this repo)
