### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Stormheg** [passkeydeveloper/passkey-authenticator-aaguids#20]
Can I include [aaguid.json](https://github.com/passkeydeveloper/passkey-authenticator-aaguids/blob/main/aaguid.json) in my open source software? (redistribute it)

**Comment by Stormheg** [comment]
@timcappalli but could I do so if I were stubborn enough? Am I allowed to embed it? 

I don't want to dynamically download it from here when it is needed, especially if it 'could go away at any time'.

**Comment by timcappalli** [comment]
go for it
