### ISSUE TITLE
Add web interface to view data

### ISSUE THREAD

**Issue by opotonniee** [passkeydeveloper/passkey-authenticator-aaguids#31]
It would be nice to add a web frontend to this project in order to easily view the content of the JSON data.
Here is a proposal:
- Code: https://github.com/opotonniee/passkey-authenticator-aaguids/tree/explorer
- View: https://opotonniee.github.io/passkey-authenticator-aaguids/explorer/

**Comment by timcappalli** [comment]
Looks great! Thanks for doing this. If you submit a PR to this repo, I can get it set up.

**Comment by opotonniee** [comment]
Here it is: #37

**Comment by timcappalli** [comment]
Thanks @opotonniee
