### ISSUE TITLE
aaguid.json should override MDS values

### ISSUE THREAD

**Issue by opotonniee** [passkeydeveloper/passkey-authenticator-aaguids#33]
Hi
As of today if an aaguid is defined in both aaguid.json and MDS, the name and icon from MDS is used in combined_aaguid.json.
This for example happens with Windows Hello aaguids.
Shouldn't the values from aaguid.json be used instead of MDS data? If not, what is the purpose of redefining an MDS aaguid in aaguid.json?

**Comment by timcappalli** [comment]
Likely just an artifact of the way the merge happens. It is not highpri for me to fix, but happy to accept a PR that fixes it.

**Comment by opotonniee** [comment]
Ditto: #34

**Comment by timcappalli** [comment]
Addressed in c48c5b4e1d3b7353103ca6d564eb2717d6d24dc4. Thanks @opotonniee
