### ISSUE TITLE
Add icon guidelines?

### ISSUE THREAD

**Issue by dagnelies** [passkeydeveloper/passkey-authenticator-aaguids#35]
Hi,

currently, the icons come in a large variety of formats. Some SVG, many PNG, and a few ones not even stating which image format, just raw data. The icons also have completely different sizes, some square with sizes ranging from 16x16 to 1000x1000 and some rectangles ranging from 58x18 to 1000x305. Many do not even use transparency but white background.

Perhaps adding some conventions like "only png" or "only svg" with a predefined size, or a few sizes, would help having more homogenous icons.

**Comment by timcappalli** [comment]
All provider icons in the passkey provider list (`aaguid.json`) are required to be SVGs and all current entries are SVG. This is documented in the README.

Except for the dark and light mode requirements, design is left up to the provider.

**Comment by dagnelies** [comment]
Oh ...right ...ah ...it's a mess because the icons imported from the [FIDO's Metadata Service (MDS)](https://fidoalliance.org/metadata/) are all PNGs as far as I can tell.
