### ISSUE TITLE
Add Protonpass

### ISSUE THREAD

**Issue by chrisdeeming** [passkeydeveloper/passkey-authenticator-aaguids#42]
The AAGUID for Protonpass is

50726f746f6e5061737350726f746f6e

I am going to point Protonpass in the direction of this issue

**Comment by timcappalli** [comment]
@chrisdeeming Proton Pass is already in the list: https://github.com/passkeydeveloper/passkey-authenticator-aaguids/pull/39

**Comment by chrisdeeming** [comment]
Oh weird. Sorry about that. I didn't find it for some reason. But also I have a different AAGUID while using their iOS app. Could they have different AAGUIDs for different platforms?

**Comment by chrisdeeming** [comment]
Apologies. I don't in fact have a different AAGUID. I just don't actually get a name or icon for some reason. 

My bad. I'll close this and find out why I'm not getting the name back. 

Sorry for wasting your time.

**Comment by chrisdeeming** [comment]
Right, sorry, I see what's happened now.

`50726f74-6f6e-5061-7373-50726f746f6e` is missing from the combined list which I'm using. I assume that's not intentional @timcappalli?

**Comment by timcappalli** [comment]
ah yeah, the action didn't fire to merge in the changes. Thanks for flagging. It should be there now. I will work on a fix for the automated flow.

**Comment by chrisdeeming** [comment]
Confirmed fixed!

<img width="149" alt="image" src="https://github.com/passkeydeveloper/passkey-authenticator-aaguids/assets/2158514/abda781b-995c-4ce0-baa4-ca493e39701e">

Looks like there were a few missing according to my local diff.
