### ISSUE TITLE
What about localized names?

### ISSUE THREAD

**Issue by rlin1** [passkeydeveloper/passkey-authenticator-aaguids#5]
all names seems to be in English language.  There might be a need to localize to some languages (e.g., Japanese, Korean, ...).  How could such localized names be expressed?

**Comment by irew** [comment]
The name could simply be a localisation key which the implementor uses to translate to their desired output. It seems unwieldy to accommodate localisation here, but I could be entirely wrong 😁.

**Comment by rlin1** [comment]
I think we want consistent authenticator names - and consistent localisations.
If we leave it to the respective implementors (by treating the strings here as a localisation key) it might lead to diverging names...

**Comment by irew** [comment]
Agree with that! Just wondering where that localisation should live and if this is the home for it.

**Comment by timcappalli** [comment]
Out of scope for this temporary solution.
