### ISSUE TITLE
How to get the correct aaguid from Windows 11?

### ISSUE THREAD

**Issue by Lamardinho** [passkeydeveloper/passkey-authenticator-aaguids#55]
I made the implementation of registration and login by passkeys. During the end of registration, I get the aaguid from RegistrationResult.getAaguid (if you know what I mean). The thing is that when registering keys in Google, iOS and BitWarden, I get a valid aaguid, but when I register a key in the Windows system, then the aaguid arrives in the form = "00000000-0000-0000-0000-000000000000", which does not correspond to this: https://passkeydeveloper.github.io/passkey-authenticator-aaguids/explorer. Please tell me what the problem could be, is this broken in Windows?

**Comment by timcappalli** [comment]
@Lamardinho this isn't a support forum for FIDO2/WebAuthn, but check to make sure you're requesting `Direct` attestation. 

passkeys.dev/discuss can be used to for further questions.

**Comment by Lamardinho** [comment]
>  this isn't a support forum for FIDO2/WebAuthn, but check to make sure you're requesting Direct attestation.
> 
> passkeys.dev/discuss can be used to for further questions.

yes, thank you, I figured it out already
