### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by mimi89999** [passkeydeveloper/passkey-authenticator-aaguids#56]
Hello,

The repo doesn't have any license and it's difficult to tell under what conditions the data in this repo can be used. The MDS licenses https://fidoalliance.org/metadata-legal-terms/ seem to be very restrictive.

> You agree that You or any software developed by You will not use any Metadata Statement or BLOB file for (i) any illegal purpose that violate any local, national, or international laws; (ii) any activities other than the Authorized Use set out in Section 1.1 above; or (iii) modifying, copying, distributing, displaying, performing, reproducing, publishing, licensing, creating derivative works from, transferring or selling any Metadata Statement or BLOB file, unless otherwise authorized by FIDO and/or the applicable Contributing Vendor in a separate written agreement.

https://fidoalliance.org/metadata-usage-terms-for-developers/

**Comment by timcappalli** [comment]
There are no current plans to add a license as it will be going away shortly.

**Comment by mimi89999** [comment]
What alternatives can be used instead?
