### ISSUE TITLE
Provider logo

### ISSUE THREAD

**Issue by irew** [passkeydeveloper/passkey-authenticator-aaguids#7]
What do we think about adding an optional value that links to branding materials that can be used to display the provider logo? 

Something like this:
```
{
    "531126d6-e717-415c-9320-3d9aa6981239": {
        "name": "Dashlane",
        "brandUrl": "https://brandfolder.com/dashlane"
    }
}
```

It can be any resource that helps with the branding, either a logo file directly or something that can provide branding materials.

This will make it simpler for an RP if they wanted to incorporate some visual representation of the provider, as we've seen with Google.

<img width="860" alt="image" src="https://github.com/passkeydeveloper/passkey-authenticator-aaguids/assets/8578329/925a7d1b-e988-4de9-a629-29e04669024b">

**Comment by timcappalli** [comment]
This isn't intended to be a long term solution so I'm hesitant to add any new fields at this point.

**Comment by christiaanbrand** [comment]
I actually don't think the idea is too silly. Not sure what other solutions
there are out there that'll address this problem: I think an unattested
AAGUID is becoming more and more likely by the day (we just removed the
allowList for the Android passkey authenticator and will be passing through
unattested AAGUID data to everyone soon).

**Comment by timcappalli** [comment]
@christiaanbrand there have been discussions in the MDS WG about spinning out an MDS Light feed for this purpose.

**Comment by christiaanbrand** [comment]
Ah, makes sense.

**Comment by timcappalli** [comment]
Revisiting this. Here's a proposal:

- Format: SVG
- Size: 256x256
- Property names: `icon_dark`, `icon_light`
- Value: embedded data URI

Thoughts @christiaanbrand @nicksteele @irew?

**Comment by irew** [comment]
Whatever works best for the dev at the RP who will be implementing this, if this is it then it looks good to me. I'm interested in what @christiaanbrand has to say as they have implemented this on their side.

**Comment by timcappalli** [comment]
@nicksteele I was hoping to stick to a single value type for the logo for consistency, easier processing by RPs, and also some level of trust as it doesn't rely on dynamic content from potentially untrusted sources. Can we stick with only embedded values for those reasons?

As for the actual value, I believe a data URI (`data:image/svg+xml;base64,blah`) would cover the values in your first example, just base64 encoded for easier processing.

**Comment by nicksteele** [comment]
I'm fine with that. 👍

**Comment by christiaanbrand** [comment]
This LGTM.

**Comment by timcappalli** [comment]
done in #10
