### ISSUE TITLE
Add required "scope" property

### ISSUE THREAD

**Issue by timcappalli** [passkeydeveloper/passkey-authenticator-aaguids#9]
One of the concerns that has come up with this list is that some passkey providers are (for good reason) limiting which RPs they send the AAGUID. This can be confusing for RPs who are testing with this list and those providers. 

This proposal is to add a new required "scope" property. 

Proposals for values:

Proposal 1: `all`, `some`
Proposal 2: `global`, `limited`
Proposal 3: `all`, `allowlist`
<what else?>

@christiaanbrand @agl @irew

**Comment by irew** [comment]
There are only a few providers here, perhaps we can just all agree to provide the AAGUID and move to a deny-list if a reason crops up? This way we wouldn't need to include this, which could come across as confusing to a new provider looking to advertise their AAGUID.

**Comment by Progdrasil** [comment]
If we do move forward on this, I would back the 3rd option since the other two are essentially trying to skirt around the term. In the documentation/schema comment though it should include that `all` does not remove the possibility of the authenticator having a deny list.

**Comment by nicksteele** [comment]
Backing Rew's point, I think we should just provide the AAGUID outright and deal with a denylist if or when it is needed.

**Comment by timcappalli** [comment]
> There are only a few providers here, perhaps we can just all agree to provide the AAGUID and move to a deny-list if a reason crops up? This way we wouldn't need to include this, which could come across as confusing to a new provider looking to advertise their AAGUID.

I don't think this is something we can get agreement on here though. So I'm trying to accommodate this interim state, which may be around for a while.

**Comment by christiaanbrand** [comment]
+1. Just provide it. I recently updated Android to do the same for google
password manager.

**Comment by timcappalli** [comment]
OK! closing.
